services:
  namenode:
    build: ./namenode
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./data:/opt/hadoop/data/
      - ./reduce_jobs:/opt/hadoop/mapreduce-jobs/
    
  resourcemanager:
    build: ./resourcemanager
    ports:
      - "8088:8088"
    volumes:
      - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./config/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
    depends_on:
      - namenode
  
  nodemanager:
    build: ./nodemanager
    ports:
      - "8042:8042"
    volumes:
      - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./config/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
    depends_on:
      - resourcemanager

  datanode1:
    build: ./datanode
    ports:
      - "9864:9864"
    volumes:
      - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
    depends_on:
      - namenode

  datanode2:
    build: ./datanode
    ports:
      - "9865:9864"
    volumes:
      - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
    depends_on:
      - namenode

  datanode3:
    build: ./datanode
    ports:
      - "9866:9864"
    volumes:
      - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
    depends_on:
      - namenode

  flask-app:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - namenode
      - resourcemanager
      - datanode1
    environment:
      - FLASK_ENV=development
      - CORS_ORIGINS=http://localhost:3000
    container_name: flask-app

  healthcare-dashboard:
    build: ./healthcare_dashboard
    ports:
      - "3000:3000"
    depends_on:
      - flask-app
    container_name: healthcare-dashboard